### ISSUE TITLE
nii 2 dcmrtstruct

### ISSUE THREAD

**Issue by wanderine** [Sikerdebaard/dcmrtstruct2nii#6]
Any chance that you can do the opposite function? I have a segmentation mask in nifti format and want to convert it to DICOM RTstruct.

**Comment by Sikerdebaard** [comment]
Unfortunately not. The following would need to happen in order to make this work:

- A nii input adapter would need to be added here: https://github.com/Sikerdebaard/dcmrtstruct2nii/tree/master/dcmrtstruct2nii/adapters/input/image
- A mask to contour / polygon converter would need to be addedd here: https://github.com/Sikerdebaard/dcmrtstruct2nii/tree/master/dcmrtstruct2nii/adapters/convert
- A dicom rt-struct output adapter would need to be added here: https://github.com/Sikerdebaard/dcmrtstruct2nii/tree/master/dcmrtstruct2nii/adapters/output
- Finally a nii2dcmrtstruct type function would need to be implemented here to glue it all together: https://github.com/Sikerdebaard/dcmrtstruct2nii/blob/master/dcmrtstruct2nii/facade/dcmrtstruct2nii.py#L29
